apollo:
  schema-file-path: schema.json
graphql:
  endpoint: https://api.start.gg/gql/alpha
  token: ${GRAPHQL_TOKEN}
jackson:
  serialization-inclusion: ALWAYS
micronaut:
  application:
    name: bracket-overlay
  router:
    static-resources:
      css:
        mapping: /css/*.css
        paths: classpath:static/css
